### ISSUE TITLE
FindTest.* Testgroup fails

### ISSUE THREAD

**Issue by fmoessbauer** [dash-project/dash#12]
Hi,

the tests in FindTest.\* currently fail:

```
[  RUN     ] FindTest.TestSimpleFind
*** stack smashing detected ***: /opt/dash/build-ci/20161015-103653/Release/bin/dash/test/mpi/dash-test-mpi terminated
[aaae69326d4c:02207] *** Process received signal ***
[aaae69326d4c:02207] Signal: Aborted (6)
[aaae69326d4c:02207] Signal code:  (-6)
```

See (travis build #97)[https://travis-ci.org/dash-project/dash/builds/167857538] for details. Branch `bug-stl-find`

**Comment by fmoessbauer** [comment]
Debug builds have shown that the bug is not caused by the dash::find implementation. Probably the team is deconstructed? 

```
[    0 DEBUG ] [ 13707 ] GlobMem.h                :465  | GlobMem.at (+g_unit) >                       | dart_gptr_t(<00000001|0001|0000|0000000000000000>) 
[    1 DEBUG ] [ 13708 ] GlobMem.h                :465  | GlobMem.at (+g_unit) >                       | dart_gptr_t(<00000001|0001|0000|0000000000000000>) 
[    0 DEBUG ] [ 13707 ] Find.h                   :82   | result value                                 | 24 
[    1 DEBUG ] [ 13708 ] Find.h                   :82   | result value                                 | 24 
[    0 DEBUG ] [ 21717 ] Team.h                   :248  | Team.unregister_deallocator()                | |- object: 0x7ffecd9db550
[    1 DEBUG ] [ 21718 ] Team.h                   :248  | Team.unregister_deallocator()                | |- object: 0x7ffcaca952d0
======
segfault...
```

**Comment by JosefSchaeffer** [comment]
I will have a closer look at this issue

**Comment by fuchsto** [comment]
There was a bug in destruction of team localities that has been fixed in #18 
Travis CI passes now.
@fmoessbauer Please verify and close this issue.

**Comment by fuchsto** [comment]
Not reproduced in development any more.

**Comment by fmoessbauer** [comment]
Unfortunately I cannot confirm this. The CI of the development branch passes because these tests are disabled. I merged the changes in development to bug-stl-find right now, but the CI does not pass. It's still the same error.

See pull request #21 and travis https://travis-ci.org/dash-project/dash/builds/168668684

Can you please have a look again.

**Comment by fuchsto** [comment]
It doesn't break at destruction of teams, looks like a problem in the algorithm.
Actually @JosefSchaeffer was assigned to the `dash::find` algorithms, I just added the implementation as a rough outline.

**Comment by fmoessbauer** [comment]
I'm pretty sure that the bug is not in the algorithm itself, as it calculates correct values (see debug output). @JosefSchaeffer and I completely refactured the old incorrect implementation during the DASH meeting. After that the unit tests passed without any error.

After moving to GitHub the bug has first occurred. The code in the old DASH repository (same implementation) is still working.

**Comment by fmoessbauer** [comment]
I can't get this bug out of my head. It seems to be related to compiler optimization, as it only occures when compiling with -Ofast. However I have no idea how to debug that...

**Comment by fuchsto** [comment]
No, it's actually simple: The array leaves the scope before all units received the result.
I added a barrier at the end of the test case to fix this.
This is curious, however, as deallocation is a collective operation with an internal barrier.

**Comment by fmoessbauer** [comment]
Ok, strange... This should definitely not be necessary.
I can't see your changes. Did you push?

**Comment by fuchsto** [comment]
Well, one bug was that `dart_allreduce` used `nbytes` instead of `count` for `MPI_Allreduce`.

**Comment by fuchsto** [comment]
Yes, got it: https://circleci.com/gh/dash-project/dash/293
